name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: xcodebuild -scheme Sworm -destination 'platform=macOS,arch=x86_64' clean test
